### ISSUE TITLE
Not sure this counts as an Issue - Any way to add the Time Tracking information into the data set

### ISSUE THREAD

**Issue by MattChandlersc** [adam-wood/powerBI-FreshService#2]
I use the time tracking that is built into the Freshservice product. I have been attempting to figure out how to get the time tracking information pulled into this data. I assume it would have to be a new table since there are several entries per ticket. Thank you for any help you may be able to provide

**Comment by adam-wood** [comment]
Hi @MattChandlersc, I have since moved on from the company where I was using FreshService. Consequently I no longer have access to the product to help with this. Perhaps more to the point, there are other things I should be spending my time on 😀.

If you want to have a go at trying this yourself, you could see if you could duplicate one of the other tables I have and modify the query to pull in time entries as per the [Time Entry API](https://api.freshservice.com/v2/#create_ticket_time_entry). You can look at the [List all Tickets](https://api.freshservice.com/v2/#view_all_ticket) API reference and compare this to the 'GetData' and 'API v2 All Tickets' queries in Power BI Query editor. **However,** I think it will get complicated as you would need to create a query that iterates over all tickets for which you want to get a time entry, as the time entry API needs to be given the ticket ID you are interested in. [This link](https://exceed.hr/blog/list-generate-and-looping-in-powerquery/) may help you get started in terms of creating a list of ticket IDs you need to retrieve time tracking data for and then setting a query to go and retrieve them. I think you may start to hit API limits with this approach though.

Good luck if you decide to give it a go.

**Comment by adam-wood** [comment]
Can't test this due to no longer using FreshService
